// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         title: "title",
 *         content: "content"
 *     }
 */
export interface KnowledgeCreateRequest {
    /** Idempotency key cho mutation (tránh double-submit). */
    "Idempotency-Key"?: string;
    title: string;
    /** Tối đa 4 MiB */
    content: string;
    content_type?: KnowledgeCreateRequest.ContentType;
    tags?: string[];
}

export namespace KnowledgeCreateRequest {
    export const ContentType = {
        Text: "text",
        Markdown: "markdown",
        Url: "url",
        File: "file",
    } as const;
    export type ContentType = (typeof ContentType)[keyof typeof ContentType];
}
