// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "name"
 *     }
 */
export interface ApiKeyCreateRequest {
    /** Idempotency key cho mutation (tránh double-submit). */
    "Idempotency-Key"?: string;
    name: string;
}
