// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface RevokeApiKeyRequest {
    id: string;
    /** Idempotency key cho mutation (tránh double-submit). */
    "Idempotency-Key"?: string;
}
