// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         display_name: "display_name"
 *     }
 */
export interface AgentCreateRequest {
    /** Idempotency key cho mutation (tránh double-submit). */
    "Idempotency-Key"?: string;
    display_name: string;
    llm_provider?: string;
    llm_model?: string;
    llm_base_url?: string;
    llm_api_key?: string;
}
