// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface AgentUpdateRequest {
    id: string;
    /** Idempotency key cho mutation (tránh double-submit). */
    "Idempotency-Key"?: string;
    display_name?: string;
    llm_provider?: string;
    llm_model?: string;
    llm_base_url?: string;
    llm_api_key?: string;
    /** Omit/null = giữ nguyên; [] = xoá. */
    knowledge_ids?: string[];
    /** Omit/null = giữ nguyên; [] = xoá. */
    enabled_tools?: string[];
    /** Omit/null = giữ nguyên; [] = xoá. Chỉ hiệu lực khi tool org_cameras được bật. */
    camera_tool_ids?: string[];
    /** Omit/null = giữ nguyên; [] = xoá. */
    mcp_dynamic_server_ids?: string[];
    /** Omit/null = giữ nguyên; {} = xoá. */
    mcp_dynamic_tool_filter?: Record<string, unknown>;
}
