// This file was auto-generated by Fern from our API Definition.

import type * as DtgAgentSdk from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "id",
 *         body: {}
 *     }
 */
export interface CreateMcpServerToolRequest {
    id: string;
    /** Idempotency key cho mutation (tránh double-submit). */
    "Idempotency-Key"?: string;
    body: DtgAgentSdk.McpServerTool;
}
