// This file was auto-generated by Fern from our API Definition.

import type * as DtgAgentSdk from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "id",
 *         kind: "rest",
 *         slug: "slug",
 *         display_name: "display_name"
 *     }
 */
export interface McpServerToolCreateRequest {
    id: string;
    /** Idempotency key cho mutation (tránh double-submit). */
    "Idempotency-Key"?: string;
    kind: McpServerToolCreateRequest.Kind;
    slug: string;
    display_name: string;
    description?: string;
    base_url?: string;
    rest_resource_path?: string;
    auth_type?: McpServerToolCreateRequest.AuthType;
    auth_config?: DtgAgentSdk.McpAuthConfig;
    endpoints?: DtgAgentSdk.McpEndpoint[];
    definition?: DtgAgentSdk.McpToolDefinition;
    sort_order?: number;
    is_active?: boolean;
}

export namespace McpServerToolCreateRequest {
    export const Kind = {
        Rest: "rest",
        Sql: "sql",
        Mongo: "mongo",
        Redis: "redis",
    } as const;
    export type Kind = (typeof Kind)[keyof typeof Kind];
    export const AuthType = {
        None: "none",
        Bearer: "bearer",
        ApiKey: "api_key",
        Basic: "basic",
        SqlQuery: "sql_query",
    } as const;
    export type AuthType = (typeof AuthType)[keyof typeof AuthType];
}
