// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface CameraUpdateRequest {
    id: string;
    /** Idempotency key cho mutation (tránh double-submit). */
    "Idempotency-Key"?: string;
    display_name?: string;
    vendor?: CameraUpdateRequest.Vendor;
    rtsp_url?: string;
    rtsp_username?: string;
    /** Rỗng/omit = giữ mật khẩu cũ; gửi giá trị mới = ghi đè. */
    rtsp_password?: string;
    vendor_config?: Record<string, unknown>;
    enabled?: boolean;
    notes?: string;
}

export namespace CameraUpdateRequest {
    export const Vendor = {
        GenericRtsp: "generic_rtsp",
        Hikvision: "hikvision",
        Ezviz: "ezviz",
        Dahua: "dahua",
        OnvifGeneric: "onvif_generic",
        Other: "other",
    } as const;
    export type Vendor = (typeof Vendor)[keyof typeof Vendor];
}
