// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         display_name: "display_name",
 *         vendor: "generic_rtsp",
 *         rtsp_url: "rtsp_url"
 *     }
 */
export interface CameraCreateRequest {
    /** Idempotency key cho mutation (tránh double-submit). */
    "Idempotency-Key"?: string;
    display_name: string;
    vendor: CameraCreateRequest.Vendor;
    rtsp_url: string;
    rtsp_username?: string;
    /** Chỉ gửi khi tạo; không bao giờ trả về trong response. */
    rtsp_password?: string;
    vendor_config?: Record<string, unknown>;
    enabled?: boolean;
    notes?: string;
}

export namespace CameraCreateRequest {
    export const Vendor = {
        GenericRtsp: "generic_rtsp",
        Hikvision: "hikvision",
        Ezviz: "ezviz",
        Dahua: "dahua",
        OnvifGeneric: "onvif_generic",
        Other: "other",
    } as const;
    export type Vendor = (typeof Vendor)[keyof typeof Vendor];
}
