// This file was auto-generated by Fern from our API Definition.

export interface Agent {
    id: string;
    display_name: string;
    status: Agent.Status;
    llm_provider?: string | undefined;
    llm_model?: string | undefined;
}

export namespace Agent {
    export const Status = {
        Created: "created",
        Running: "running",
        Stopped: "stopped",
        Unknown: "unknown",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
