// This file was auto-generated by Fern from our API Definition.

export interface Agent {
    id: string;
    display_name: string;
    status: Agent.Status;
    llm_provider?: string | undefined;
    llm_model?: string | undefined;
    llm_base_url?: string | undefined;
    knowledge_ids?: string[] | undefined;
    enabled_tools?: string[] | undefined;
    /** UUID camera ORG được phép khi bật tool org_cameras (điền vào dtg_camera_tool_ids). */
    camera_tool_ids?: string[] | undefined;
    mcp_dynamic_server_ids?: string[] | undefined;
    mcp_dynamic_tool_filter?: Record<string, unknown> | undefined;
}

export namespace Agent {
    export const Status = {
        Created: "created",
        Running: "running",
        Stopped: "stopped",
        Unknown: "unknown",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
