// This file was auto-generated by Fern from our API Definition.

export interface ApiKey {
    id?: string | undefined;
    name?: string | undefined;
    token_prefix?: string | undefined;
    created_at?: string | undefined;
    last_used_at?: string | undefined;
}
