// This file was auto-generated by Fern from our API Definition.

export interface ApiKeyCreateResponse {
    id?: string | undefined;
    name?: string | undefined;
    secret?: string | undefined;
}
