// This file was auto-generated by Fern from our API Definition.

/**
 * Camera IP/RTSP thuộc organization. `rtsp_password` KHÔNG được trả về
 * (redact) — chỉ có `has_rtsp_password`. `vendor_config` là JSON tùy hãng
 * (channel/stream, device_serial, ...).
 */
export interface Camera {
    id: string;
    display_name: string;
    vendor: Camera.Vendor;
    vendor_label?: string | undefined;
    rtsp_url?: string | undefined;
    rtsp_username?: string | undefined;
    has_rtsp_password?: boolean | undefined;
    /** JSON cấu hình tùy hãng (channel, stream, ...) */
    vendor_config?: Record<string, unknown> | undefined;
    enabled?: boolean | undefined;
    notes?: string | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
}

export namespace Camera {
    export const Vendor = {
        GenericRtsp: "generic_rtsp",
        Hikvision: "hikvision",
        Ezviz: "ezviz",
        Dahua: "dahua",
        OnvifGeneric: "onvif_generic",
        Other: "other",
    } as const;
    export type Vendor = (typeof Vendor)[keyof typeof Vendor];
}
