// This file was auto-generated by Fern from our API Definition.

export interface ChannelConfig {
    type: ChannelConfig.Type;
    env: Record<string, string>;
}

export namespace ChannelConfig {
    export const Type = {
        Telegram: "telegram",
        Discord: "discord",
        Slack: "slack",
        GoogleChat: "google_chat",
        Whatsapp: "whatsapp",
        Signal: "signal",
        Sms: "sms",
        Email: "email",
        Homeassistant: "homeassistant",
        Mattermost: "mattermost",
        Matrix: "matrix",
        Dingtalk: "dingtalk",
        Feishu: "feishu",
        Wecom: "wecom",
        WecomCallback: "wecom_callback",
        Weixin: "weixin",
        Bluebubbles: "bluebubbles",
        Qq: "qq",
        Yuanbao: "yuanbao",
        Teams: "teams",
        Line: "line",
        Webhook: "webhook",
        MsgraphWebhook: "msgraph_webhook",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
