// This file was auto-generated by Fern from our API Definition.

export interface ChatCompletion {
    id?: string | undefined;
    object?: string | undefined;
    created?: number | undefined;
    model?: string | undefined;
    choices?: Record<string, unknown>[] | undefined;
    usage?: ChatCompletion.Usage | undefined;
}

export namespace ChatCompletion {
    export interface Usage {
        prompt_tokens?: number | undefined;
        completion_tokens?: number | undefined;
        total_tokens?: number | undefined;
    }
}
