// This file was auto-generated by Fern from our API Definition.

export interface ChatMessage {
    role: ChatMessage.Role;
    content: string;
}

export namespace ChatMessage {
    export const Role = {
        System: "system",
        User: "user",
        Assistant: "assistant",
        Tool: "tool",
    } as const;
    export type Role = (typeof Role)[keyof typeof Role];
}
