// This file was auto-generated by Fern from our API Definition.

export const EnvelopeStatus = {
    Ok: "ok",
    Error: "error",
} as const;
export type EnvelopeStatus = (typeof EnvelopeStatus)[keyof typeof EnvelopeStatus];
