// This file was auto-generated by Fern from our API Definition.

export interface Knowledge {
    id?: string | undefined;
    title?: string | undefined;
    content_type?: Knowledge.ContentType | undefined;
    tags?: string[] | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
}

export namespace Knowledge {
    export const ContentType = {
        Text: "text",
        Markdown: "markdown",
        Url: "url",
        File: "file",
    } as const;
    export type ContentType = (typeof ContentType)[keyof typeof ContentType];
}
