// This file was auto-generated by Fern from our API Definition.

import type * as DtgAgentSdk from "../index.js";

export interface KnowledgeDetail extends DtgAgentSdk.Knowledge {
    content?: string | undefined;
}
