// This file was auto-generated by Fern from our API Definition.

/**
 * Thông tin xác thực / kết nối DB. Khi tạo tool có thể gửi secret (token, password, dsn).
 * Response list/get chỉ trả field đã redact (không phơi token/password/dsn).
 */
export interface McpAuthConfig {
    token?: string | undefined;
    header_name?: string | undefined;
    username?: string | undefined;
    password?: string | undefined;
    driver?: string | undefined;
    dsn?: string | undefined;
    read_only?: boolean | undefined;
    max_rows?: number | undefined;
    engine?: string | undefined;
    host?: string | undefined;
    port?: number | undefined;
    database?: string | undefined;
    ssl_mode?: string | undefined;
    extra_params?: string | undefined;
    raw_dsn?: string | undefined;
    auth_source?: string | undefined;
    tls?: boolean | undefined;
    db_index?: number | undefined;
}
