// This file was auto-generated by Fern from our API Definition.

export interface McpEndpointParam {
    name?: string | undefined;
    type?: McpEndpointParam.Type | undefined;
    in?: McpEndpointParam.In | undefined;
    required?: boolean | undefined;
}

export namespace McpEndpointParam {
    export const Type = {
        String: "string",
        Integer: "integer",
        Boolean: "boolean",
        Number: "number",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
    export const In = {
        Query: "query",
        Path: "path",
        Header: "header",
        Body: "body",
    } as const;
    export type In = (typeof In)[keyof typeof In];
}
