// This file was auto-generated by Fern from our API Definition.

import type * as DtgAgentSdk from "../index.js";

export interface McpEndpoint {
    /** GET | POST | PUT | PATCH | DELETE (REST) */
    method?: string | undefined;
    path?: string | undefined;
    name?: string | undefined;
    description?: string | undefined;
    params?: DtgAgentSdk.McpEndpointParam[] | undefined;
    body_schema?: string | undefined;
    sql_template?: string | undefined;
    mongo_op?: McpEndpoint.MongoOp | undefined;
    collection?: string | undefined;
    filter_json?: string | undefined;
    pipeline_json?: string | undefined;
    redis_command?: string | undefined;
    /** JSON array template, e.g. ["user:{id}"] */
    redis_args?: string | undefined;
}

export namespace McpEndpoint {
    export const MongoOp = {
        Find: "find",
        FindOne: "findOne",
        Aggregate: "aggregate",
        InsertOne: "insertOne",
        UpdateOne: "updateOne",
        DeleteOne: "deleteOne",
    } as const;
    export type MongoOp = (typeof MongoOp)[keyof typeof MongoOp];
}
