// This file was auto-generated by Fern from our API Definition.

export interface McpServerTool {
    id?: string | undefined;
    mcp_server_id?: string | undefined;
    kind?: McpServerTool.Kind | undefined;
    slug?: string | undefined;
    display_name?: string | undefined;
    description?: string | undefined;
    base_url?: string | undefined;
    auth_type?: McpServerTool.AuthType | undefined;
    /** Thông tin xác thực (có thể chứa secret — không phơi raw token ở list). */
    auth_config?: Record<string, unknown> | undefined;
    endpoints?: Record<string, unknown>[] | undefined;
    sort_order?: number | undefined;
    is_active?: boolean | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
}

export namespace McpServerTool {
    export const Kind = {
        Rest: "rest",
        Sql: "sql",
        Mongo: "mongo",
        Redis: "redis",
    } as const;
    export type Kind = (typeof Kind)[keyof typeof Kind];
    export const AuthType = {
        None: "none",
        Bearer: "bearer",
        ApiKey: "api_key",
        Basic: "basic",
        SqlQuery: "sql_query",
    } as const;
    export type AuthType = (typeof AuthType)[keyof typeof AuthType];
}
