// This file was auto-generated by Fern from our API Definition.

export interface McpServer {
    id?: string | undefined;
    name?: string | undefined;
    description?: string | undefined;
    tool_count?: number | undefined;
    created_at?: string | undefined;
    updated_at?: string | undefined;
}
