// This file was auto-generated by Fern from our API Definition.

/**
 * Ràng buộc bảo mật / kích thước cho REST tool.
 */
export interface McpToolDefinition {
    max_timeout_ms?: number | undefined;
    max_response_kb?: number | undefined;
    schema_validate?: boolean | undefined;
    allowed_hosts?: string[] | undefined;
}
