// This file was auto-generated by Fern from our API Definition.

import type * as DtgAgentSdk from "../index.js";

export interface ModelList {
    object?: string | undefined;
    data?: DtgAgentSdk.Model[] | undefined;
}
