// This file was auto-generated by Fern from our API Definition.

export interface OkResponse {
    revoked?: boolean | undefined;
    deleted?: boolean | undefined;
    started?: boolean | undefined;
    stopped?: boolean | undefined;
}
