// This file was auto-generated by Fern from our API Definition.

/**
 * Lỗi dạng OpenAI-compatible từ gateway `/v1/*` và `/webhook/*`.
 */
export interface OpenAiCompatError {
    error?: OpenAiCompatError.Error_ | undefined;
}

export namespace OpenAiCompatError {
    export interface Error_ {
        message?: string | undefined;
        type?: string | undefined;
        code?: string | undefined;
    }
}
