// This file was auto-generated by Fern from our API Definition.

export interface OrganizationMember {
    account_id?: string | undefined;
    email?: string | undefined;
    role?: OrganizationMember.Role | undefined;
}

export namespace OrganizationMember {
    export const Role = {
        Owner: "owner",
        Admin: "admin",
        Member: "member",
        Reader: "reader",
    } as const;
    export type Role = (typeof Role)[keyof typeof Role];
}
