// This file was auto-generated by Fern from our API Definition.

export interface Organization {
    id?: string | undefined;
    slug?: string | undefined;
    display_name?: string | undefined;
    description?: string | undefined;
}
