// This file was auto-generated by Fern from our API Definition.

export interface UnauthorizedErrorBody {
    status?: UnauthorizedErrorBody.Status | undefined;
    code?: UnauthorizedErrorBody.Code | undefined;
    message: string;
    data?: unknown | undefined;
    trace_id: string;
    timestamp: string;
}

export namespace UnauthorizedErrorBody {
    export const Status = {
        Error: "error",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    export const Code = {
        Unauthorized: "unauthorized",
        Forbidden: "forbidden",
        NotFound: "not_found",
        InvalidRequest: "invalid_request",
        RateLimited: "rate_limited",
        PayloadTooLarge: "payload_too_large",
        ServiceUnavailable: "service_unavailable",
        Internal: "internal",
    } as const;
    export type Code = (typeof Code)[keyof typeof Code];
}
