// This file was auto-generated by Fern from our API Definition.

import type * as DtgAgentSdk from "../../../index.js";

export interface ListMcpServersResponse {
    data?: DtgAgentSdk.McpServer[] | undefined;
    status: DtgAgentSdk.EnvelopeStatus;
    code: string;
    message: string;
    trace_id: string;
    timestamp: string;
}
