// This file was auto-generated by Fern from our API Definition.

import { DtgAgentSdkClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("AgentsClient", () => {
    test("listAgents", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: "ok",
            code: "code",
            message: "message",
            data: [
                {
                    id: "id",
                    display_name: "display_name",
                    status: "created",
                    llm_provider: "llm_provider",
                    llm_model: "llm_model",
                },
            ],
            trace_id: "trace_id",
            timestamp: "2024-01-15T09:30:00Z",
        };

        server.mockEndpoint().get("/api/v1/agents").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.agents.listAgents();
        expect(response).toEqual(rawResponseBody);
    });

    test("createAgent", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { display_name: "display_name" };
        const rawResponseBody = {
            status: "ok",
            code: "code",
            message: "message",
            data: {
                id: "id",
                display_name: "display_name",
                status: "created",
                llm_provider: "llm_provider",
                llm_model: "llm_model",
            },
            trace_id: "trace_id",
            timestamp: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .post("/api/v1/agents")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.createAgent({
            display_name: "display_name",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getAgent", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: "ok",
            code: "code",
            message: "message",
            data: {
                id: "id",
                display_name: "display_name",
                status: "created",
                llm_provider: "llm_provider",
                llm_model: "llm_model",
            },
            trace_id: "trace_id",
            timestamp: "2024-01-15T09:30:00Z",
        };

        server.mockEndpoint().get("/api/v1/agents/id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.agents.getAgent({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("deleteAgent", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: "ok",
            code: "code",
            message: "message",
            data: { revoked: true, deleted: true, started: true, stopped: true },
            trace_id: "trace_id",
            timestamp: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .delete("/api/v1/agents/id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.deleteAgent({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("updateAgent", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            status: "ok",
            code: "code",
            message: "message",
            data: {
                id: "id",
                display_name: "display_name",
                status: "created",
                llm_provider: "llm_provider",
                llm_model: "llm_model",
            },
            trace_id: "trace_id",
            timestamp: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .patch("/api/v1/agents/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.updateAgent({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("startAgent", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: "ok",
            code: "code",
            message: "message",
            data: { revoked: true, deleted: true, started: true, stopped: true },
            trace_id: "trace_id",
            timestamp: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .post("/api/v1/agents/id/start")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.startAgent({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("stopAgent", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: "ok",
            code: "code",
            message: "message",
            data: { revoked: true, deleted: true, started: true, stopped: true },
            trace_id: "trace_id",
            timestamp: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .post("/api/v1/agents/id/stop")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.stopAgent({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getAgentChannels", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: "ok",
            code: "code",
            message: "message",
            data: [{ type: "telegram", env: { key: "value" } }],
            trace_id: "trace_id",
            timestamp: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .get("/api/v1/agents/id/channels")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.getAgentChannels({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("updateAgentChannels", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            status: "ok",
            code: "code",
            message: "message",
            data: [{ type: "telegram", env: { key: "value" } }],
            trace_id: "trace_id",
            timestamp: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .put("/api/v1/agents/id/channels")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.updateAgentChannels({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listAgentModels", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { object: "object", data: [{ id: "id", object: "object", owned_by: "owned_by" }] };

        server.mockEndpoint().get("/api/v1/models").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.agents.listAgentModels();
        expect(response).toEqual(rawResponseBody);
    });
});
