// This file was auto-generated by Fern from our API Definition.

import * as DtgAgentSdk from "../../src/api/index";
import { DtgAgentSdkClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("AgentsClient", () => {
    test("listAgents (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: "ok",
            code: "code",
            message: "message",
            data: [
                {
                    id: "id",
                    display_name: "display_name",
                    status: "created",
                    llm_provider: "llm_provider",
                    llm_model: "llm_model",
                    llm_base_url: "llm_base_url",
                    knowledge_ids: ["knowledge_ids"],
                    enabled_tools: ["enabled_tools"],
                    mcp_dynamic_server_ids: ["mcp_dynamic_server_ids"],
                    mcp_dynamic_tool_filter: { key: "value" },
                },
            ],
            trace_id: "trace_id",
            timestamp: "2024-01-15T09:30:00Z",
        };

        server.mockEndpoint().get("/api/v1/agents").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.agents.listAgents();
        expect(response).toEqual(rawResponseBody);
    });

    test("listAgents (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/api/v1/agents").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.agents.listAgents();
        }).rejects.toThrow(DtgAgentSdk.UnauthorizedError);
    });

    test("listAgents (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/api/v1/agents").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.agents.listAgents();
        }).rejects.toThrow(DtgAgentSdk.TooManyRequestsError);
    });

    test("createAgent (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { display_name: "display_name" };
        const rawResponseBody = {
            status: "ok",
            code: "code",
            message: "message",
            data: {
                id: "id",
                display_name: "display_name",
                status: "created",
                llm_provider: "llm_provider",
                llm_model: "llm_model",
                llm_base_url: "llm_base_url",
                knowledge_ids: ["knowledge_ids"],
                enabled_tools: ["enabled_tools"],
                mcp_dynamic_server_ids: ["mcp_dynamic_server_ids"],
                mcp_dynamic_tool_filter: { key: "value" },
            },
            trace_id: "trace_id",
            timestamp: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .post("/api/v1/agents")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.createAgent({
            display_name: "display_name",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createAgent (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { display_name: "display_name" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/api/v1/agents")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.createAgent({
                display_name: "display_name",
            });
        }).rejects.toThrow(DtgAgentSdk.BadRequestError);
    });

    test("createAgent (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { display_name: "display_name" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/api/v1/agents")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.createAgent({
                display_name: "display_name",
            });
        }).rejects.toThrow(DtgAgentSdk.UnauthorizedError);
    });

    test("createAgent (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { display_name: "display_name" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/api/v1/agents")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.createAgent({
                display_name: "display_name",
            });
        }).rejects.toThrow(DtgAgentSdk.ForbiddenError);
    });

    test("createAgent (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { display_name: "display_name" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/api/v1/agents")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(413)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.createAgent({
                display_name: "display_name",
            });
        }).rejects.toThrow(DtgAgentSdk.ContentTooLargeError);
    });

    test("createAgent (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { display_name: "display_name" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/api/v1/agents")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.createAgent({
                display_name: "display_name",
            });
        }).rejects.toThrow(DtgAgentSdk.TooManyRequestsError);
    });

    test("getAgent (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: "ok",
            code: "code",
            message: "message",
            data: {
                id: "id",
                display_name: "display_name",
                status: "created",
                llm_provider: "llm_provider",
                llm_model: "llm_model",
                llm_base_url: "llm_base_url",
                knowledge_ids: ["knowledge_ids"],
                enabled_tools: ["enabled_tools"],
                mcp_dynamic_server_ids: ["mcp_dynamic_server_ids"],
                mcp_dynamic_tool_filter: { key: "value" },
            },
            trace_id: "trace_id",
            timestamp: "2024-01-15T09:30:00Z",
        };

        server.mockEndpoint().get("/api/v1/agents/id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.agents.getAgent({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getAgent (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/api/v1/agents/id").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.agents.getAgent({
                id: "id",
            });
        }).rejects.toThrow(DtgAgentSdk.UnauthorizedError);
    });

    test("getAgent (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/api/v1/agents/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.agents.getAgent({
                id: "id",
            });
        }).rejects.toThrow(DtgAgentSdk.NotFoundError);
    });

    test("deleteAgent (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: "ok",
            code: "code",
            message: "message",
            data: { revoked: true, deleted: true, started: true, stopped: true },
            trace_id: "trace_id",
            timestamp: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .delete("/api/v1/agents/id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.deleteAgent({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("deleteAgent (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/api/v1/agents/id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.deleteAgent({
                id: "id",
            });
        }).rejects.toThrow(DtgAgentSdk.UnauthorizedError);
    });

    test("deleteAgent (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/api/v1/agents/id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.deleteAgent({
                id: "id",
            });
        }).rejects.toThrow(DtgAgentSdk.ForbiddenError);
    });

    test("deleteAgent (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/api/v1/agents/id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.deleteAgent({
                id: "id",
            });
        }).rejects.toThrow(DtgAgentSdk.NotFoundError);
    });

    test("updateAgent (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            status: "ok",
            code: "code",
            message: "message",
            data: {
                id: "id",
                display_name: "display_name",
                status: "created",
                llm_provider: "llm_provider",
                llm_model: "llm_model",
                llm_base_url: "llm_base_url",
                knowledge_ids: ["knowledge_ids"],
                enabled_tools: ["enabled_tools"],
                mcp_dynamic_server_ids: ["mcp_dynamic_server_ids"],
                mcp_dynamic_tool_filter: { key: "value" },
            },
            trace_id: "trace_id",
            timestamp: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .patch("/api/v1/agents/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.updateAgent({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("updateAgent (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/api/v1/agents/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.updateAgent({
                id: "id",
            });
        }).rejects.toThrow(DtgAgentSdk.BadRequestError);
    });

    test("updateAgent (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/api/v1/agents/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.updateAgent({
                id: "id",
            });
        }).rejects.toThrow(DtgAgentSdk.UnauthorizedError);
    });

    test("updateAgent (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/api/v1/agents/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.updateAgent({
                id: "id",
            });
        }).rejects.toThrow(DtgAgentSdk.ForbiddenError);
    });

    test("updateAgent (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/api/v1/agents/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.updateAgent({
                id: "id",
            });
        }).rejects.toThrow(DtgAgentSdk.NotFoundError);
    });

    test("updateAgent (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/api/v1/agents/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.updateAgent({
                id: "id",
            });
        }).rejects.toThrow(DtgAgentSdk.TooManyRequestsError);
    });

    test("startAgent", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: "ok",
            code: "code",
            message: "message",
            data: { revoked: true, deleted: true, started: true, stopped: true },
            trace_id: "trace_id",
            timestamp: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .post("/api/v1/agents/id/start")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.startAgent({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("stopAgent", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: "ok",
            code: "code",
            message: "message",
            data: { revoked: true, deleted: true, started: true, stopped: true },
            trace_id: "trace_id",
            timestamp: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .post("/api/v1/agents/id/stop")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.stopAgent({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getAgentChannels", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: "ok",
            code: "code",
            message: "message",
            data: [{ type: "telegram", env: { key: "value" } }],
            trace_id: "trace_id",
            timestamp: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .get("/api/v1/agents/id/channels")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.getAgentChannels({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("updateAgentChannels", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            status: "ok",
            code: "code",
            message: "message",
            data: [{ type: "telegram", env: { key: "value" } }],
            trace_id: "trace_id",
            timestamp: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .put("/api/v1/agents/id/channels")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.updateAgentChannels({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listAgentModels", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { object: "object", data: [{ id: "id", object: "object", owned_by: "owned_by" }] };

        server.mockEndpoint().get("/api/v1/models").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.agents.listAgentModels();
        expect(response).toEqual(rawResponseBody);
    });
});
