// This file was auto-generated by Fern from our API Definition.

import { DtgAgentSdkClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ApiKeysClient", () => {
    test("listApiKeys", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: "ok",
            code: "code",
            message: "message",
            data: [
                {
                    id: "id",
                    name: "name",
                    token_prefix: "token_prefix",
                    created_at: "2024-01-15T09:30:00Z",
                    last_used_at: "2024-01-15T09:30:00Z",
                },
            ],
            trace_id: "trace_id",
            timestamp: "2024-01-15T09:30:00Z",
        };

        server.mockEndpoint().get("/api/v1/api-keys").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.apiKeys.listApiKeys();
        expect(response).toEqual(rawResponseBody);
    });

    test("createApiKey", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {
            status: "ok",
            code: "code",
            message: "message",
            data: { id: "id", name: "name", secret: "secret" },
            trace_id: "trace_id",
            timestamp: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .post("/api/v1/api-keys")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.apiKeys.createApiKey({
            name: "name",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("revokeApiKey", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: "ok",
            code: "code",
            message: "message",
            data: { revoked: true, deleted: true, started: true, stopped: true },
            trace_id: "trace_id",
            timestamp: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .delete("/api/v1/api-keys/id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.apiKeys.revokeApiKey({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });
});
