// This file was auto-generated by Fern from our API Definition.

import * as DtgAgentSdk from "../../src/api/index";
import { DtgAgentSdkClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("CamerasClient", () => {
    test("listCameras (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: "ok",
            code: "code",
            message: "message",
            data: [
                {
                    id: "id",
                    display_name: "display_name",
                    vendor: "generic_rtsp",
                    vendor_label: "vendor_label",
                    rtsp_url: "rtsp_url",
                    rtsp_username: "rtsp_username",
                    has_rtsp_password: true,
                    vendor_config: { key: "value" },
                    enabled: true,
                    notes: "notes",
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                },
            ],
            trace_id: "trace_id",
            timestamp: "2024-01-15T09:30:00Z",
        };

        server.mockEndpoint().get("/api/v1/cameras").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.cameras.listCameras();
        expect(response).toEqual(rawResponseBody);
    });

    test("listCameras (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/api/v1/cameras").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.cameras.listCameras();
        }).rejects.toThrow(DtgAgentSdk.UnauthorizedError);
    });

    test("listCameras (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/api/v1/cameras").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.cameras.listCameras();
        }).rejects.toThrow(DtgAgentSdk.TooManyRequestsError);
    });

    test("createCamera (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { display_name: "display_name", vendor: "generic_rtsp", rtsp_url: "rtsp_url" };
        const rawResponseBody = {
            status: "ok",
            code: "code",
            message: "message",
            data: {
                id: "id",
                display_name: "display_name",
                vendor: "generic_rtsp",
                vendor_label: "vendor_label",
                rtsp_url: "rtsp_url",
                rtsp_username: "rtsp_username",
                has_rtsp_password: true,
                vendor_config: { key: "value" },
                enabled: true,
                notes: "notes",
                created_at: "2024-01-15T09:30:00Z",
                updated_at: "2024-01-15T09:30:00Z",
            },
            trace_id: "trace_id",
            timestamp: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .post("/api/v1/cameras")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.cameras.createCamera({
            display_name: "display_name",
            vendor: "generic_rtsp",
            rtsp_url: "rtsp_url",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createCamera (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { display_name: "display_name", vendor: "generic_rtsp", rtsp_url: "rtsp_url" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/api/v1/cameras")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.cameras.createCamera({
                display_name: "display_name",
                vendor: "generic_rtsp",
                rtsp_url: "rtsp_url",
            });
        }).rejects.toThrow(DtgAgentSdk.BadRequestError);
    });

    test("createCamera (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { display_name: "display_name", vendor: "generic_rtsp", rtsp_url: "rtsp_url" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/api/v1/cameras")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.cameras.createCamera({
                display_name: "display_name",
                vendor: "generic_rtsp",
                rtsp_url: "rtsp_url",
            });
        }).rejects.toThrow(DtgAgentSdk.UnauthorizedError);
    });

    test("createCamera (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { display_name: "display_name", vendor: "generic_rtsp", rtsp_url: "rtsp_url" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/api/v1/cameras")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.cameras.createCamera({
                display_name: "display_name",
                vendor: "generic_rtsp",
                rtsp_url: "rtsp_url",
            });
        }).rejects.toThrow(DtgAgentSdk.ForbiddenError);
    });

    test("createCamera (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { display_name: "display_name", vendor: "generic_rtsp", rtsp_url: "rtsp_url" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/api/v1/cameras")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(413)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.cameras.createCamera({
                display_name: "display_name",
                vendor: "generic_rtsp",
                rtsp_url: "rtsp_url",
            });
        }).rejects.toThrow(DtgAgentSdk.ContentTooLargeError);
    });

    test("createCamera (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { display_name: "display_name", vendor: "generic_rtsp", rtsp_url: "rtsp_url" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/api/v1/cameras")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.cameras.createCamera({
                display_name: "display_name",
                vendor: "generic_rtsp",
                rtsp_url: "rtsp_url",
            });
        }).rejects.toThrow(DtgAgentSdk.TooManyRequestsError);
    });

    test("getCamera (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: "ok",
            code: "code",
            message: "message",
            data: {
                id: "id",
                display_name: "display_name",
                vendor: "generic_rtsp",
                vendor_label: "vendor_label",
                rtsp_url: "rtsp_url",
                rtsp_username: "rtsp_username",
                has_rtsp_password: true,
                vendor_config: { key: "value" },
                enabled: true,
                notes: "notes",
                created_at: "2024-01-15T09:30:00Z",
                updated_at: "2024-01-15T09:30:00Z",
            },
            trace_id: "trace_id",
            timestamp: "2024-01-15T09:30:00Z",
        };

        server.mockEndpoint().get("/api/v1/cameras/id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.cameras.getCamera({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getCamera (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/api/v1/cameras/id").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.cameras.getCamera({
                id: "id",
            });
        }).rejects.toThrow(DtgAgentSdk.UnauthorizedError);
    });

    test("getCamera (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/api/v1/cameras/id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.cameras.getCamera({
                id: "id",
            });
        }).rejects.toThrow(DtgAgentSdk.NotFoundError);
    });

    test("deleteCamera (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: "ok",
            code: "code",
            message: "message",
            data: { revoked: true, deleted: true, started: true, stopped: true },
            trace_id: "trace_id",
            timestamp: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .delete("/api/v1/cameras/id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.cameras.deleteCamera({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("deleteCamera (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/api/v1/cameras/id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.cameras.deleteCamera({
                id: "id",
            });
        }).rejects.toThrow(DtgAgentSdk.UnauthorizedError);
    });

    test("deleteCamera (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/api/v1/cameras/id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.cameras.deleteCamera({
                id: "id",
            });
        }).rejects.toThrow(DtgAgentSdk.ForbiddenError);
    });

    test("deleteCamera (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/api/v1/cameras/id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.cameras.deleteCamera({
                id: "id",
            });
        }).rejects.toThrow(DtgAgentSdk.NotFoundError);
    });

    test("updateCamera (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            status: "ok",
            code: "code",
            message: "message",
            data: {
                id: "id",
                display_name: "display_name",
                vendor: "generic_rtsp",
                vendor_label: "vendor_label",
                rtsp_url: "rtsp_url",
                rtsp_username: "rtsp_username",
                has_rtsp_password: true,
                vendor_config: { key: "value" },
                enabled: true,
                notes: "notes",
                created_at: "2024-01-15T09:30:00Z",
                updated_at: "2024-01-15T09:30:00Z",
            },
            trace_id: "trace_id",
            timestamp: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .patch("/api/v1/cameras/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.cameras.updateCamera({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("updateCamera (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/api/v1/cameras/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.cameras.updateCamera({
                id: "id",
            });
        }).rejects.toThrow(DtgAgentSdk.BadRequestError);
    });

    test("updateCamera (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/api/v1/cameras/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.cameras.updateCamera({
                id: "id",
            });
        }).rejects.toThrow(DtgAgentSdk.UnauthorizedError);
    });

    test("updateCamera (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/api/v1/cameras/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.cameras.updateCamera({
                id: "id",
            });
        }).rejects.toThrow(DtgAgentSdk.ForbiddenError);
    });

    test("updateCamera (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/api/v1/cameras/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.cameras.updateCamera({
                id: "id",
            });
        }).rejects.toThrow(DtgAgentSdk.NotFoundError);
    });

    test("updateCamera (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/api/v1/cameras/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.cameras.updateCamera({
                id: "id",
            });
        }).rejects.toThrow(DtgAgentSdk.TooManyRequestsError);
    });
});
