// This file was auto-generated by Fern from our API Definition.

import { DtgAgentSdkClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("GatewayClient", () => {
    test("listModels", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { object: "object", data: [{ id: "id", object: "object", owned_by: "owned_by" }] };

        server.mockEndpoint().get("/v1/models").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.gateway.listModels();
        expect(response).toEqual(rawResponseBody);
    });

    test("createChatCompletion", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { model: "model", messages: [{ role: "system", content: "content" }] };
        const rawResponseBody = {
            id: "id",
            object: "object",
            created: 1,
            model: "model",
            choices: [{ key: "value" }],
            usage: { prompt_tokens: 1, completion_tokens: 1, total_tokens: 1 },
        };

        server
            .mockEndpoint()
            .post("/v1/chat/completions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.gateway.createChatCompletion({
            model: "model",
            messages: [
                {
                    role: "system",
                    content: "content",
                },
            ],
        });
        expect(response).toEqual(rawResponseBody);
    });
});
