// This file was auto-generated by Fern from our API Definition.

import * as DtgAgentSdk from "../../src/api/index";
import { DtgAgentSdkClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("GatewayClient", () => {
    test("listModels", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { object: "object", data: [{ id: "id", object: "object", owned_by: "owned_by" }] };

        server.mockEndpoint().get("/v1/models").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.gateway.listModels();
        expect(response).toEqual(rawResponseBody);
    });

    test("createChatCompletion (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { model: "model", messages: [{ role: "system", content: "content" }] };
        const rawResponseBody = {
            id: "id",
            object: "object",
            created: 1,
            model: "model",
            choices: [{ key: "value" }],
            usage: { prompt_tokens: 1, completion_tokens: 1, total_tokens: 1 },
        };

        server
            .mockEndpoint()
            .post("/v1/chat/completions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.gateway.createChatCompletion({
            model: "model",
            messages: [
                {
                    role: "system",
                    content: "content",
                },
            ],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createChatCompletion (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            model: "model",
            messages: [
                { role: "system", content: "content" },
                { role: "system", content: "content" },
            ],
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/chat/completions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gateway.createChatCompletion({
                model: "model",
                messages: [
                    {
                        role: "system",
                        content: "content",
                    },
                    {
                        role: "system",
                        content: "content",
                    },
                ],
            });
        }).rejects.toThrow(DtgAgentSdk.UnauthorizedError);
    });

    test("createChatCompletion (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            model: "model",
            messages: [
                { role: "system", content: "content" },
                { role: "system", content: "content" },
            ],
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/chat/completions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gateway.createChatCompletion({
                model: "model",
                messages: [
                    {
                        role: "system",
                        content: "content",
                    },
                    {
                        role: "system",
                        content: "content",
                    },
                ],
            });
        }).rejects.toThrow(DtgAgentSdk.ForbiddenError);
    });

    test("createChatCompletion (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            model: "model",
            messages: [
                { role: "system", content: "content" },
                { role: "system", content: "content" },
            ],
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/chat/completions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gateway.createChatCompletion({
                model: "model",
                messages: [
                    {
                        role: "system",
                        content: "content",
                    },
                    {
                        role: "system",
                        content: "content",
                    },
                ],
            });
        }).rejects.toThrow(DtgAgentSdk.NotFoundError);
    });

    test("createChatCompletion (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            model: "model",
            messages: [
                { role: "system", content: "content" },
                { role: "system", content: "content" },
            ],
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/chat/completions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(413)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gateway.createChatCompletion({
                model: "model",
                messages: [
                    {
                        role: "system",
                        content: "content",
                    },
                    {
                        role: "system",
                        content: "content",
                    },
                ],
            });
        }).rejects.toThrow(DtgAgentSdk.ContentTooLargeError);
    });

    test("createChatCompletion (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            model: "model",
            messages: [
                { role: "system", content: "content" },
                { role: "system", content: "content" },
            ],
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/chat/completions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gateway.createChatCompletion({
                model: "model",
                messages: [
                    {
                        role: "system",
                        content: "content",
                    },
                    {
                        role: "system",
                        content: "content",
                    },
                ],
            });
        }).rejects.toThrow(DtgAgentSdk.TooManyRequestsError);
    });

    test("createChatCompletionByAgentPath (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { messages: [{ role: "system", content: "content" }] };
        const rawResponseBody = {
            id: "id",
            object: "object",
            created: 1,
            model: "model",
            choices: [{ key: "value" }],
            usage: { prompt_tokens: 1, completion_tokens: 1, total_tokens: 1 },
        };

        server
            .mockEndpoint()
            .post("/webhook/agent_id/v1/chat/completions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.gateway.createChatCompletionByAgentPath({
            agent_id: "agent_id",
            messages: [
                {
                    role: "system",
                    content: "content",
                },
            ],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createChatCompletionByAgentPath (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            messages: [
                { role: "system", content: "content" },
                { role: "system", content: "content" },
            ],
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/webhook/agent_id/v1/chat/completions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gateway.createChatCompletionByAgentPath({
                agent_id: "agent_id",
                messages: [
                    {
                        role: "system",
                        content: "content",
                    },
                    {
                        role: "system",
                        content: "content",
                    },
                ],
            });
        }).rejects.toThrow(DtgAgentSdk.UnauthorizedError);
    });

    test("createChatCompletionByAgentPath (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            messages: [
                { role: "system", content: "content" },
                { role: "system", content: "content" },
            ],
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/webhook/agent_id/v1/chat/completions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gateway.createChatCompletionByAgentPath({
                agent_id: "agent_id",
                messages: [
                    {
                        role: "system",
                        content: "content",
                    },
                    {
                        role: "system",
                        content: "content",
                    },
                ],
            });
        }).rejects.toThrow(DtgAgentSdk.ForbiddenError);
    });

    test("createChatCompletionByAgentPath (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            messages: [
                { role: "system", content: "content" },
                { role: "system", content: "content" },
            ],
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/webhook/agent_id/v1/chat/completions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gateway.createChatCompletionByAgentPath({
                agent_id: "agent_id",
                messages: [
                    {
                        role: "system",
                        content: "content",
                    },
                    {
                        role: "system",
                        content: "content",
                    },
                ],
            });
        }).rejects.toThrow(DtgAgentSdk.NotFoundError);
    });

    test("createChatCompletionByAgentPath (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            messages: [
                { role: "system", content: "content" },
                { role: "system", content: "content" },
            ],
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/webhook/agent_id/v1/chat/completions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(413)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gateway.createChatCompletionByAgentPath({
                agent_id: "agent_id",
                messages: [
                    {
                        role: "system",
                        content: "content",
                    },
                    {
                        role: "system",
                        content: "content",
                    },
                ],
            });
        }).rejects.toThrow(DtgAgentSdk.ContentTooLargeError);
    });

    test("createChatCompletionByAgentPath (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            messages: [
                { role: "system", content: "content" },
                { role: "system", content: "content" },
            ],
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/webhook/agent_id/v1/chat/completions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.gateway.createChatCompletionByAgentPath({
                agent_id: "agent_id",
                messages: [
                    {
                        role: "system",
                        content: "content",
                    },
                    {
                        role: "system",
                        content: "content",
                    },
                ],
            });
        }).rejects.toThrow(DtgAgentSdk.TooManyRequestsError);
    });
});
