// This file was auto-generated by Fern from our API Definition.

import { DtgAgentSdkClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("KnowledgeClient", () => {
    test("listKnowledge", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: "ok",
            code: "code",
            message: "message",
            data: [
                {
                    id: "id",
                    title: "title",
                    content_type: "text",
                    tags: ["tags"],
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                },
            ],
            trace_id: "trace_id",
            timestamp: "2024-01-15T09:30:00Z",
        };

        server.mockEndpoint().get("/api/v1/knowledge").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.knowledge.listKnowledge();
        expect(response).toEqual(rawResponseBody);
    });

    test("createKnowledge", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { title: "title", content: "content" };
        const rawResponseBody = {
            status: "ok",
            code: "code",
            message: "message",
            data: {
                id: "id",
                title: "title",
                content_type: "text",
                tags: ["tags"],
                created_at: "2024-01-15T09:30:00Z",
                updated_at: "2024-01-15T09:30:00Z",
            },
            trace_id: "trace_id",
            timestamp: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .post("/api/v1/knowledge")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.knowledge.createKnowledge({
            title: "title",
            content: "content",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getKnowledge", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: "ok",
            code: "code",
            message: "message",
            data: {
                id: "id",
                title: "title",
                content_type: "text",
                tags: ["tags"],
                created_at: "2024-01-15T09:30:00Z",
                updated_at: "2024-01-15T09:30:00Z",
                content: "content",
            },
            trace_id: "trace_id",
            timestamp: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .get("/api/v1/knowledge/id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.knowledge.getKnowledge({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("deleteKnowledge", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: "ok",
            code: "code",
            message: "message",
            data: { revoked: true, deleted: true, started: true, stopped: true },
            trace_id: "trace_id",
            timestamp: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .delete("/api/v1/knowledge/id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.knowledge.deleteKnowledge({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });
});
