// This file was auto-generated by Fern from our API Definition.

import * as DtgAgentSdk from "../../src/api/index";
import { DtgAgentSdkClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("McpServersClient", () => {
    test("listMcpServers", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: "ok",
            code: "code",
            message: "message",
            data: [
                {
                    id: "id",
                    name: "name",
                    description: "description",
                    tool_count: 1,
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                },
            ],
            trace_id: "trace_id",
            timestamp: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .get("/api/v1/mcp-servers")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.mcpServers.listMcpServers();
        expect(response).toEqual(rawResponseBody);
    });

    test("createMcpServer", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {
            status: "ok",
            code: "code",
            message: "message",
            data: {
                id: "id",
                name: "name",
                description: "description",
                tool_count: 1,
                created_at: "2024-01-15T09:30:00Z",
                updated_at: "2024-01-15T09:30:00Z",
            },
            trace_id: "trace_id",
            timestamp: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .post("/api/v1/mcp-servers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.mcpServers.createMcpServer({
            name: "name",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listMcpServerTools", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: "ok",
            code: "code",
            message: "message",
            data: [
                {
                    id: "id",
                    mcp_server_id: "mcp_server_id",
                    kind: "rest",
                    slug: "slug",
                    display_name: "display_name",
                    description: "description",
                    base_url: "base_url",
                    rest_resource_path: "rest_resource_path",
                    auth_type: "none",
                    endpoints: [{}],
                    sort_order: 1,
                    is_active: true,
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                },
            ],
            trace_id: "trace_id",
            timestamp: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .get("/api/v1/mcp-servers/id/tools")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.mcpServers.listMcpServerTools({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createMcpServerTool (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { kind: "rest", slug: "slug", display_name: "display_name" };
        const rawResponseBody = {
            status: "ok",
            code: "code",
            message: "message",
            data: {
                id: "id",
                mcp_server_id: "mcp_server_id",
                kind: "rest",
                slug: "slug",
                display_name: "display_name",
                description: "description",
                base_url: "base_url",
                rest_resource_path: "rest_resource_path",
                auth_type: "none",
                auth_config: {
                    token: "token",
                    header_name: "header_name",
                    username: "username",
                    password: "password",
                    driver: "driver",
                    dsn: "dsn",
                    read_only: true,
                    max_rows: 1,
                    engine: "engine",
                    host: "host",
                    port: 1,
                    database: "database",
                    ssl_mode: "ssl_mode",
                    extra_params: "extra_params",
                    raw_dsn: "raw_dsn",
                    auth_source: "auth_source",
                    tls: true,
                    db_index: 1,
                },
                endpoints: [{}],
                definition: {
                    max_timeout_ms: 1,
                    max_response_kb: 1,
                    schema_validate: true,
                    allowed_hosts: ["allowed_hosts"],
                },
                sort_order: 1,
                is_active: true,
                created_at: "2024-01-15T09:30:00Z",
                updated_at: "2024-01-15T09:30:00Z",
            },
            trace_id: "trace_id",
            timestamp: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .post("/api/v1/mcp-servers/id/tools")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.mcpServers.createMcpServerTool({
            id: "id",
            kind: "rest",
            slug: "slug",
            display_name: "display_name",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createMcpServerTool (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { kind: "rest", slug: "slug", display_name: "display_name" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/api/v1/mcp-servers/id/tools")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.mcpServers.createMcpServerTool({
                id: "id",
                kind: "rest",
                slug: "slug",
                display_name: "display_name",
            });
        }).rejects.toThrow(DtgAgentSdk.BadRequestError);
    });

    test("createMcpServerTool (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { kind: "rest", slug: "slug", display_name: "display_name" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/api/v1/mcp-servers/id/tools")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.mcpServers.createMcpServerTool({
                id: "id",
                kind: "rest",
                slug: "slug",
                display_name: "display_name",
            });
        }).rejects.toThrow(DtgAgentSdk.UnauthorizedError);
    });

    test("createMcpServerTool (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { kind: "rest", slug: "slug", display_name: "display_name" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/api/v1/mcp-servers/id/tools")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.mcpServers.createMcpServerTool({
                id: "id",
                kind: "rest",
                slug: "slug",
                display_name: "display_name",
            });
        }).rejects.toThrow(DtgAgentSdk.ForbiddenError);
    });

    test("createMcpServerTool (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { kind: "rest", slug: "slug", display_name: "display_name" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/api/v1/mcp-servers/id/tools")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.mcpServers.createMcpServerTool({
                id: "id",
                kind: "rest",
                slug: "slug",
                display_name: "display_name",
            });
        }).rejects.toThrow(DtgAgentSdk.NotFoundError);
    });
});
