// This file was auto-generated by Fern from our API Definition.

import { DtgAgentSdkClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("McpServersClient", () => {
    test("listMcpServers", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: "ok",
            code: "code",
            message: "message",
            data: [
                {
                    id: "id",
                    name: "name",
                    description: "description",
                    tool_count: 1,
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                },
            ],
            trace_id: "trace_id",
            timestamp: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .get("/api/v1/mcp-servers")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.mcpServers.listMcpServers();
        expect(response).toEqual(rawResponseBody);
    });

    test("createMcpServer", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {
            status: "ok",
            code: "code",
            message: "message",
            data: {
                id: "id",
                name: "name",
                description: "description",
                tool_count: 1,
                created_at: "2024-01-15T09:30:00Z",
                updated_at: "2024-01-15T09:30:00Z",
            },
            trace_id: "trace_id",
            timestamp: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .post("/api/v1/mcp-servers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.mcpServers.createMcpServer({
            name: "name",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listMcpServerTools", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: "ok",
            code: "code",
            message: "message",
            data: [
                {
                    id: "id",
                    mcp_server_id: "mcp_server_id",
                    kind: "rest",
                    slug: "slug",
                    display_name: "display_name",
                    description: "description",
                    base_url: "base_url",
                    auth_type: "none",
                    auth_config: { key: "value" },
                    endpoints: [{ key: "value" }],
                    sort_order: 1,
                    is_active: true,
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                },
            ],
            trace_id: "trace_id",
            timestamp: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .get("/api/v1/mcp-servers/id/tools")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.mcpServers.listMcpServerTools({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("createMcpServerTool", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            status: "ok",
            code: "code",
            message: "message",
            data: {
                id: "id",
                mcp_server_id: "mcp_server_id",
                kind: "rest",
                slug: "slug",
                display_name: "display_name",
                description: "description",
                base_url: "base_url",
                auth_type: "none",
                auth_config: { key: "value" },
                endpoints: [{ key: "value" }],
                sort_order: 1,
                is_active: true,
                created_at: "2024-01-15T09:30:00Z",
                updated_at: "2024-01-15T09:30:00Z",
            },
            trace_id: "trace_id",
            timestamp: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .post("/api/v1/mcp-servers/id/tools")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.mcpServers.createMcpServerTool({
            id: "id",
            body: {},
        });
        expect(response).toEqual(rawResponseBody);
    });
});
