// This file was auto-generated by Fern from our API Definition.

import * as DtgAgentSdk from "../../src/api/index";
import { DtgAgentSdkClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("OrganizationsClient", () => {
    test("getOrganization (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: "ok",
            code: "code",
            message: "message",
            data: { id: "id", slug: "slug", display_name: "display_name", description: "description" },
            trace_id: "trace_id",
            timestamp: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .get("/api/v1/organizations/id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.organizations.getOrganization({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getOrganization (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/api/v1/organizations/id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.getOrganization({
                id: "id",
            });
        }).rejects.toThrow(DtgAgentSdk.UnauthorizedError);
    });

    test("getOrganization (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/api/v1/organizations/id")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.getOrganization({
                id: "id",
            });
        }).rejects.toThrow(DtgAgentSdk.ForbiddenError);
    });

    test("getOrganization (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/api/v1/organizations/id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.getOrganization({
                id: "id",
            });
        }).rejects.toThrow(DtgAgentSdk.NotFoundError);
    });

    test("listOrganizationMembers (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: "ok",
            code: "code",
            message: "message",
            data: [{ account_id: "account_id", email: "email", role: "owner" }],
            trace_id: "trace_id",
            timestamp: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .get("/api/v1/organizations/id/members")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.organizations.listOrganizationMembers({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listOrganizationMembers (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/api/v1/organizations/id/members")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.listOrganizationMembers({
                id: "id",
            });
        }).rejects.toThrow(DtgAgentSdk.UnauthorizedError);
    });

    test("listOrganizationMembers (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/api/v1/organizations/id/members")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.organizations.listOrganizationMembers({
                id: "id",
            });
        }).rejects.toThrow(DtgAgentSdk.ForbiddenError);
    });
});
