// This file was auto-generated by Fern from our API Definition.

import { DtgAgentSdkClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("OrganizationsClient", () => {
    test("getOrganization", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: "ok",
            code: "code",
            message: "message",
            data: { id: "id", slug: "slug", display_name: "display_name", description: "description" },
            trace_id: "trace_id",
            timestamp: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .get("/api/v1/organizations/id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.organizations.getOrganization({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("listOrganizationMembers", async () => {
        const server = mockServerPool.createServer();
        const client = new DtgAgentSdkClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            status: "ok",
            code: "code",
            message: "message",
            data: [{ account_id: "account_id", email: "email", role: "owner" }],
            trace_id: "trace_id",
            timestamp: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .get("/api/v1/organizations/id/members")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.organizations.listOrganizationMembers({
            id: "id",
        });
        expect(response).toEqual(rawResponseBody);
    });
});
