// This file was auto-generated by Fern from our API Definition.

import { AgentsClient } from "./api/resources/agents/client/Client.js";
import { ApiKeysClient } from "./api/resources/apiKeys/client/Client.js";
import { CamerasClient } from "./api/resources/cameras/client/Client.js";
import { GatewayClient } from "./api/resources/gateway/client/Client.js";
import { KnowledgeClient } from "./api/resources/knowledge/client/Client.js";
import { McpServersClient } from "./api/resources/mcpServers/client/Client.js";
import { OrganizationsClient } from "./api/resources/organizations/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";
import * as core from "./core/index.js";

export declare namespace DtgAgentSdkClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class DtgAgentSdkClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<DtgAgentSdkClient.Options>;
    protected _gateway: GatewayClient | undefined;
    protected _agents: AgentsClient | undefined;
    protected _apiKeys: ApiKeysClient | undefined;
    protected _organizations: OrganizationsClient | undefined;
    protected _knowledge: KnowledgeClient | undefined;
    protected _cameras: CamerasClient | undefined;
    protected _mcpServers: McpServersClient | undefined;

    constructor(options: DtgAgentSdkClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get gateway(): GatewayClient {
        return (this._gateway ??= new GatewayClient(this._options));
    }

    public get agents(): AgentsClient {
        return (this._agents ??= new AgentsClient(this._options));
    }

    public get apiKeys(): ApiKeysClient {
        return (this._apiKeys ??= new ApiKeysClient(this._options));
    }

    public get organizations(): OrganizationsClient {
        return (this._organizations ??= new OrganizationsClient(this._options));
    }

    public get knowledge(): KnowledgeClient {
        return (this._knowledge ??= new KnowledgeClient(this._options));
    }

    public get cameras(): CamerasClient {
        return (this._cameras ??= new CamerasClient(this._options));
    }

    public get mcpServers(): McpServersClient {
        return (this._mcpServers ??= new McpServersClient(this._options));
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
                getAuthHeaders: async () => (await this._options.authProvider.getAuthRequest()).headers,
            },
            requestOptions,
        );
    }
}
