// This file was auto-generated by Fern from our API Definition.

export const DtgAgentSdkEnvironment = {
    Production: "https://agents.dtgsoft.vn",
} as const;

export type DtgAgentSdkEnvironment = typeof DtgAgentSdkEnvironment.Production;
