// This file was auto-generated by Fern from our API Definition.

import type * as DtgAgentSdk from "../../../../index.js";

/**
 * @example
 *     {
 *         model: "model",
 *         messages: [{
 *                 role: "system",
 *                 content: "content"
 *             }]
 *     }
 */
export interface ChatCompletionRequest {
    /** Session tùy chỉnh phía client. */
    "X-Hermes-Session-Id"?: string;
    /** Thread tùy chỉnh phía client. */
    "X-Hermes-Thread-Id"?: string;
    /** ID của agent (UUID). */
    model: string;
    messages: DtgAgentSdk.ChatMessage[];
    temperature?: number;
    stream?: boolean;
    session_id?: string;
    thread_id?: string;
}
