// This file was auto-generated by Fern from our API Definition.

import type * as DtgAgentSdk from "../../../../index.js";

/**
 * @example
 *     {
 *         agent_id: "agent_id",
 *         messages: [{
 *                 role: "system",
 *                 content: "content"
 *             }]
 *     }
 */
export interface WebhookChatCompletionRequest {
    agent_id: string;
    /** Tuỳ chọn; agent đã xác định bởi path. */
    model?: string;
    messages: DtgAgentSdk.ChatMessage[];
    temperature?: number;
    stream?: boolean;
    /** Session ID tùy chỉnh phía client (được orchestrator namespace theo user để chống xung đột). */
    session_id?: string;
    /** Thread ID con trong session (tùy chỉnh phía client, namespace theo user). */
    thread_id?: string;
}
